version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:12
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: workout_app_test
    steps:
      - checkout
      - run: npm install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm test
workflows:
  build_test:
    jobs:
      - build_and_test
