version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost:5432/workout_app_test
      - image: postgres:13.0
        environment:
          POSTGRES_USER: root
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: workout_app_test

    steps:
      - checkout
workflows:
  build-and-test:
    jobs:
      - build
      - node/test:
          requires:
            - build
