version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: circleci/postgres:13.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: "workout_app_test"
    steps:
      - checkout
workflows:
  build-and-test:
    jobs:
      - build
      - node/test:
          requires:
            - build
