version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6-alpine-ram
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
    steps:
      - checkout
workflows:
  build-and-test:
    jobs:
      - build
      - node/test:
          requires:
            - build
