version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/workout_app_test
      - image: postgres
        environment:
          PSQL_HOST: postgres
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: workout_app_test
          TEST_DATABASE_URL: postgresql://root@localhost/workout_app_test
    steps:
      - checkout
workflows:
  build-and-test:
    jobs:
      - build
      - node/test:
          requires:
            - build
