version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/workout_app_test
      - image: circleci/postgres:9.6
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: circle_test

    steps:
      - checkout
workflows:
  build-and-test:
    jobs:
      - build
      - node/test:
          requires:
            - build
